# Generated by Django 5.1.1 on 2024-09-19 17:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(3)])),
                ('last_name', models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(3)])),
                ('password', models.CharField(max_length=255, unique=True)),
                ('enrollment_date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.CreateModel(
            name='TeachersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(3)])),
                ('last_name', models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(3)])),
                ('password', models.CharField(max_length=255, unique=True)),
                ('department', models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(8)])),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
            },
        ),
    ]
