# Generated by Django 5.1.1 on 2024-09-20 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments_groups', '0001_initial'),
        ('students_teachers', '0002_departmentsmodel_alter_teachersmodel_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachersmodel',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher', to='departments_groups.departmentsmodel'),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student', to='departments_groups.groupsmodel'),
        ),
        migrations.DeleteModel(
            name='DepartmentsModel',
        ),
    ]
